### ISSUE TITLE
Pembuatan database

### ISSUE THREAD

**Issue by TEAMMIKRO** [TEAMMIKRO/Pengukuran_Tinggi_Badan_Berbasis_Audio#5]

**Comment by atillahabil** [comment]
![Image](https://github.com/TEAMMIKRO/Pengukuran_Tinggi_Badan_Berbasis_Audio/assets/169013520/da50fe44-b769-4083-bfa6-920948570c6b)



![Image](https://github.com/TEAMMIKRO/Pengukuran_Tinggi_Badan_Berbasis_Audio/assets/169013520/c8171744-8317-4ffb-8136-0b19c1bda7fc)
